import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const read=p=>fs.readFileSync(p,'utf8');
const page=read('dist/index.html'),app=read('dist/app.js'),worker=read('dist/sw.js');
const release=JSON.parse(read('dist/updates.json'));
const catalog=JSON.parse(read('dist/catalog.json'));
new vm.Script(app,{filename:'app.js'});
new vm.Script(worker,{filename:'sw.js'});
assert.match(page,/id="wallRequestForm"/);
assert.match(page,/id="firstVisitGuide"/);
assert.match(page,/id="resumeSection"/);
assert.match(page,/id="everything"/);
const exploreStart=page.indexOf('<section id="everything"');
const exploreEnd=page.indexOf('</section>',exploreStart);
const exploreSection=page.slice(exploreStart,exploreEnd);
assert.match(exploreSection,/id="missionInviteHeading">Get to Know AWE Missions/);
assert.match(exploreSection,/href="#mission">Learn About Our Mission/);
assert.match(exploreSection,/href="https:\/\/www\.givesendgo\.com\/awemissions"/);
assert.ok(exploreSection.indexOf('mission-invite')<exploreSection.indexOf('discover-grid'),'Mission banner should be discoverable before the tile grid');

assert.match(page,/id="whatsNew"/);
assert.match(page,/id="newContentNotice"/);
assert.match(page,/id="updateReady"/);
assert.match(page,/id="prayerIntake"/);
assert.match(page,/id="updateDot"/);
assert.match(page,/Version 1\.2\.2/);
assert.equal(release.version,'1.2.2');
assert.ok(release.items.length>=3);
assert.ok(catalog.games.length>0);
const mainNav=page.match(/<nav id="mainNav"[^>]*>([\s\S]*?)<\/nav>/)?.[1]||'';
assert.doesNotMatch(mainNav,/>Story Time<\/a>/,'Story Time should not be in the top navigation');
const studyStart=page.indexOf('<section id="study"');
const storyStart=page.indexOf('<section id="storyTime"');
const gamesStart=page.indexOf('<section id="games"');
assert.ok(studyStart>0 && storyStart>studyStart && gamesStart>storyStart,'Story Time must appear inside Learn & Play before Games');
assert.match(page,/class="resource-choice story-choice" href="#storyTime"/);
assert.match(app,/functions\/v1\/awe-prayer/);
assert.doesNotMatch(app,/window\.location\.href='mailto:contact@awemissions\.org/);
assert.doesNotMatch(page,/href="https:\/\/awemissions\.org\/missionary"/);
const allIds=new Map();
for(const match of page.matchAll(/\bid="([^"]+)"/g)){allIds.set(match[1],(allIds.get(match[1])||0)+1)}
for(const [id,count] of allIds)assert.equal(count,1,'Duplicate HTML id '+id);
for(const match of page.matchAll(/href="#([^"]+)"/g)){const id=match[1];if(id)assert.ok(allIds.has(id),'Broken anchor #'+id)}
for(const item of release.items)assert.ok(item.url && item.title && item.description,'Incomplete release entry');
console.log('AWE Faith QA passed: scripts, links, features, catalog and release feed.');
